title: Việc làm
subtitle: "Tìm việc làm phù hợp nhanh chóng, hiệu quả."
description: "Kinh nghiệm và chia sẻ khi tìm việc làm."
author: Vu Nguyen
language: vi
timezone: UTC

url: https://www.123vieclam.com
root: /
permalink: news/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: hexojs
google_analytics: UA-48498357-3
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: hexojs
github: hexojs/hexo
